import { SafeUrl } from "@angular/platform-browser";

export class TBLShamelEmployee {
    public id :number ;
    public Payrol_ID:  string ;    
    public Computer_ID:number ;
    public Global_ID:  string ;
    public Insurance_ID  :number ;
    public FName :string  ;
    public LName :string ;
    public Father :string ;
    public Mother :string ;
    public Birth_Place: string;
    public BirthDate :string ;
    public Kayd_Place:string ;
    public PhoneNum:string ;
    public ID_Number:string;
    public Sex_Name:string ;
    public MartialState_ID:number;
    public Sex_ID:number;
    public Nationality_ID:number;
    public City_ID:number;
    public Emp_IN_Military_Service:number;        
    public Area_ID:number;
    public MiniArea_ID:number ;
    public StreetOrVillage_ID:number;
    public ManualAddress:string ;
    public MartialState_Name:string ;   
    public EducationLast_ID:number ;
    public JobStateFirst_ID:number ;
    public JobStateLast_ID:number ;
    public MalakState_Name:string;
    public InsuranceSalary:number;
    public Accounter_ID:number ;
    public AccounterSerial:number;
    public Rem1:string;
    public Rem2:string;
    public Rem3:string;
    public Qarar_Num:string;
    public QararDate:string;
    public Photo:string;    
    public EnterUserName:string;
    public EnterDate:string;
    public EnterTime:string;
    public ModifyUserName:string;
    public ModifyDate:string;
    public ModifyTime:string;
    public FullName:string;
    public Nationality_Name:string;
    public City_Name:string;
    public Area_Name:string;
    public MiniArea_Name :string;
    public StreetOrVillage_Name  :string;
    public Accounter_Name  :string;
    public Certificate_Name  :string;
    public Specification_Name  :string;
    public JobName_Name  :string;
    public Class_Name  :string;
    public Salary   :number;
    public BeginDate  :string;
    public ChangeReason_Name :string;
   
    constructor(){
        this. id =0;
         this. Payrol_ID ='';    
     this. Computer_ID=0;
     this. Global_ID='';
     this. Insurance_ID  =0 ;
     this. FName ='';
     this. LName  ='';
     this. Father  ='';
     this. Mother  ='';
     this. Birth_Place ='';
     this. BirthDate  ='';
     this. Kayd_Place ='';
     this. PhoneNum ='';
     this. ID_Number ='';
     this. Sex_Name='';
     this. MartialState_ID=0;
     this. Sex_ID=0;
     this. Nationality_ID=0;
     this.  City_ID=0;
     this.  Emp_IN_Military_Service=0;
     this. Area_ID=0;
     this. MiniArea_ID=0;
     this. StreetOrVillage_ID=0;
     this. ManualAddress='';
     this. MartialState_Name='';
     this. EducationLast_ID=0;
     this. JobStateFirst_ID=0;
     this. JobStateLast_ID=0;
     this. MalakState_Name='';
     this. InsuranceSalary=0;
     this. Accounter_ID=0;
     this. AccounterSerial=0;
     this. Rem1='';
     this. Rem2='';
     this.Rem3='';
     this. Qarar_Num='';
     this.QararDate='';
     this.Photo='';
     this.EnterUserName='';
     this.EnterDate='';
     this.EnterTime='';
     this.ModifyUserName='';
     this.ModifyDate='';
     this.ModifyTime='';
     this.FullName='';
     this.Nationality_Name='';
     this.City_Name='';
     this.Area_Name='';
     this.MiniArea_Name='';
     this.StreetOrVillage_Name='';
     this.Accounter_Name  ='';
     this.Certificate_Name  ='';
     this.Specification_Name  ='';
     this.JobName_Name  ='';
     this.Class_Name  ='';
     this.Salary   =0;
     this.BeginDate  ='';
    this.ChangeReason_Name ='';
      }

}